/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytiempho.model.frontend;
import java.io.UnsupportedEncodingException;
import java.util.*;
import java.security.*;
import java.util.logging.Level;
import java.math.*;
import java.util.logging.Logger;
import quanlytiempho.model.backend.connectiondb.Connectiondb;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author Acer
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setSize(500,400);
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        KeyAdapter ka=new KeyAdapter()
        {
          @Override
          public void keyPressed(KeyEvent ke)
          {
              if(ke.getKeyCode()==KeyEvent.VK_ENTER)
              {
                  jButton1.doClick();
              }
          }
        };
        jTextField1.addKeyListener(ka);
        jTextField2.addKeyListener(ka);
    }
            Connectiondb con=new Connectiondb();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginForm");
        setSize(getPreferredSize());
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Đăng Nhập");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 142, 55);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 90, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 80, 22);

        jTextField1.setText("taikhoan2");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 90, 150, 40);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\LAB2\\download 5.png")); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 280, 160, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\LAB2\\iconfinder_user-alt_285645 (1).png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 80, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\LAB2\\download 4.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 160, 50, 50);

        jTextField2.setText("miyuki2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 170, 150, 40);

        jCheckBox1.setText("Hiển thị mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(320, 230, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String username=jTextField1.getText();
            String password=jTextField2.getText();
            byte[] passw=password.getBytes("UTF-8");
            MessageDigest md=MessageDigest.getInstance("MD5");
            byte[] respw=md.digest(passw);
            BigInteger num=new BigInteger(1,respw);
            String res=num.toString(16);
            while(res.length()<32)
            {
                res="0"+res;
            }
            String query="Select * from taikhoan where tentaikhoan='"+username+"' ";
            String query1="Select matkhau from taikhoan where tentaikhoan='"+username+"'";
            ResultSet r=con.sqlres(query);
            System.out.println(res);
          
            if(r.first()==false)
            {
                JOptionPane.showMessageDialog(this,"Tên tài khoản không hợp lệ");
                 jTextField1.requestFocus();
            }
            ResultSet r1=con.sqlres(query1);
            while(r1.next())
            {
               if(!res.equals(r1.getString("matkhau")))
               {
                   JOptionPane.showMessageDialog(this,"Mật khẩu không hợp lệ.");
                   jTextField2.requestFocus();
               }
               else
               {
              this.dispose();
               JOptionPane.showMessageDialog(this,"Đăng nhập thành công.");
                new MainFrameForm(username).setVisible(true);
               }
            }
           
            
           
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
      boolean t=jCheckBox1.isSelected();
      if(t)
      {
          jTextField2.setEchoChar((char)0);
      }
      else
      {
          jTextField2.setEchoChar('*');
      }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    // End of variables declaration//GEN-END:variables
}
