/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytiempho.model.frontend;
import quanlytiempho.model.backend.connectiondb.Connectiondb;
import quanlytiempho.model.backend.quanlynhanvien.nhanvien;
import quanlytiempho.model.backend.quanlynhanvien.nhanvienBUS;
import java.time.LocalDate;
import javax.swing.JOptionPane;
public class themnhanvien extends javax.swing.JFrame {

    /**
     * Creates new form themnhanvien
     */
    public themnhanvien() {
        initComponents();
         this.setSize(500,400);
        this.setLocationRelativeTo(null);
        this.setTitle("Thêm quyền");
        j1.setText(qlnv.getNextID());
        j1.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    nhanvienBUS qlnv=new nhanvienBUS();
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        j2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        j5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm nhân viên");
        getContentPane().setLayout(null);

        jLabel1.setText("Mã nhân viên:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 90, 30);
        getContentPane().add(j1);
        j1.setBounds(110, 50, 80, 30);

        jLabel2.setText("Tên nhân viên:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 50, 90, 30);

        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(370, 50, 80, 30);

        jLabel3.setText("Ngày sinh:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 70, 40);

        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(110, 130, 80, 30);

        jLabel4.setText("Số điện thoại:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 140, 90, 20);
        getContentPane().add(j4);
        j4.setBounds(370, 130, 80, 30);

        jLabel5.setText("Địa chỉ:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 220, 70, 20);

        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });
        getContentPane().add(j5);
        j5.setBounds(210, 210, 90, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\add (2).png")); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 310, 100, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Downloads\\remove (1).png")); // NOI18N
        jButton2.setText("Đóng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 310, 110, 39);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
  private static boolean validatePhoneNumber(String phoneNo) {
		
		if (phoneNo.matches("\\d{11}")) return true;
		else return false;
		
	}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String idnhanvien=j1.getText();
        String tennhanvien=j2.getText();
        LocalDate ngaysinh = LocalDate.parse(j3.getText());
        String dienthoai=j4.getText();
        String diachi=j5.getText();
        if(idnhanvien==""||tennhanvien==""||ngaysinh==null||dienthoai==""||diachi=="")
        {
            JOptionPane.showMessageDialog(this,"Không được để trống thông tin cần nhập.");
        }
        else if(validatePhoneNumber(dienthoai)==false)
        {
            JOptionPane.showMessageDialog(this,"Số điện thoại không hợp lệ");
        }
        else
        {
        qlnv.addnhanvien(new nhanvien(idnhanvien,tennhanvien,dienthoai,ngaysinh,diachi));
        JOptionPane.showMessageDialog(this,"Đã thêm nhân viên thành công.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themnhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
